
-- Create all the tables needed to support the capital palette art competition scoring

CREATE TABLE REF_MANUFACTURER (
	ID				INT NOT NULL,
	LABEL			VARCHAR(100) NOT NULL,
	DESCRIPTION		VARCHAR(255) NULL,
	CONSTRAINT PK_REF_MAN_ID PRIMARY KEY (ID)
	);

CREATE TABLE REF_ARMY_FACTION (
	ID				INT NOT NULL,
	LABEL			VARCHAR(100) NOT NULL,
	DESCRIPTION		VARCHAR(255) NULL,
	GAME_SYSTEM_ID	INT NULL,
	CONSTRAINT PK_ARMY_FAC_ID PRIMARY KEY (ID),
	CONSTRAINT FK_FACTION_GAMESYS_ID FOREIGN KEY (GAME_SYSTEM_ID)
		REFERENCES	LT_GAME_SYSTEM (ID)
	) ;
	
CREATE TABLE LT_APPEARANCE_CATEGORY (
	ID					INT NOT NULL,
	LABEL				VARCHAR(50) NOT NULL,
	DESCRIPTION			VARCHAR(255) NULL,
	CONSTRAINT	PK_APPR_CAT_ID PRIMARY KEY (ID)
	);
	
CREATE TABLE APPEARANCE_ENTRY (
	ID					INT NOT NULL,
	ARTIST_ID			INT NOT NULL,
	EVENT_ID			INT NOT NULL,
	LABEL				VARCHAR(100) NOT NULL,
	DESCRIPTION			VARCHAR(255) NULL,
	CATEGORY_ID			INT NOT NULL,
	MANUFACTURER_ID		INT NULL,
	ARMY_FACTION_ID		INT NULL,
	NOTE				VARCHAR(255) NULL,
	LAST_MODIFIED_BY 	VARCHAR(55) NOT NULL,
	LAST_MODIFIED_DATE 	DATETIME NOT NULL,
	CREATED_BY 			VARCHAR(55) NOT NULL,
	CREATED_DATE 		DATETIME NOT NULL,
	CONSTRAINT	PK_APP_ENTRY_ID PRIMARY KEY (ID),
	CONSTRAINT 	FK_APP_ENTRY_MAN_ID FOREIGN KEY (MANUFACTURER_ID)
		REFERENCES REF_MANUFACTURER (ID),
	CONSTRAINT 	FK_APP_ENTRY_ARM_FAC_ID FOREIGN KEY (ARMY_FACTION_ID)
		REFERENCES	REF_ARMY_FACTION (ID)
	);

CREATE TABLE APPEARANCE_SCORE (
	ID					INT NOT NULL,
	ENTRY_ID			INT NOT NULL,
	JUDGE_ID			INT NOT NULL,
	BASE_SCORE			INT NOT NULL,
	SCORE_MODIFIER		INT NULL,
	JUDGE_COMMENT		TEXT NULL,
	LAST_MODIFIED_BY 	VARCHAR(55) NOT NULL,
	LAST_MODIFIED_DATE 	DATETIME NOT NULL,
	CREATED_BY 			VARCHAR(55) NOT NULL,
	CREATED_DATE 		DATETIME NOT NULL,
	CONSTRAINT	PK_APP_SCORE_ID PRIMARY KEY (ID),
	CONSTRAINT	FK_APP_SCORE_ENTRY_ID FOREIGN KEY (ENTRY_ID)
		REFERENCES APPEARANCE_ENTRY (ID),
	CONSTRAINT	FK_APP_SCORE_JUDGE_ID FOREIGN KEY (JUDGE_ID)
		REFERENCES USER (ID)
	);

-- DML FOR THE Lookup tables

INSERT INTO LT_APPEARANCE_CATEGORY (ID, LABEL, DESCRIPTION)
VALUES
	(1,'Army Appearance','Game system army appearance score'),
	(2,'SciFi - Small','Single small miniature'),
	(3,'SciFi - Large','Single large miniature'),
	(4,'SciFi - Collection','Multiple miniatures in a collection, squad, or diorama'),
	(5,'Fantasy - Small','Single small miniature'),
	(6,'Fantasy - Large','Single large miniature'),
	(7,'Fantasy - Collection','Multiple miniatures in a collection, squad, or diorama'),
	(8,'Historical- Small','Single small miniature'),
	(9,'Historical- Large','Single large miniature'),
	(10,'Historical- Collection','Multiple miniatures in a collection, squad, or diorama')
	;


INSERT INTO CHANGELOG
	(SCRIPT, RUN_DATE)
VALUES
	('010002002_create_capital_palette_tables.sql',NOW())
;