/*
-- Update event table to set weekend_badge_req to 0 (no) for selected events

-- Date: 2013-04-09 22:32
*/
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 1;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 2;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 3;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 4;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 5;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 6;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 27;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 28;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 29;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 61;
UPDATE EVENT SET IS_WEEKEND_BADGE_REQ = 0 WHERE ID = 62;


INSERT INTO CHANGELOG
	(SCRIPT, RUN_DATE)
VALUES
	('010001010_Update_Weekend_Badge_Req_Values.sql',NOW())
;