
-- Insert the new warma events
INSERT INTO EVENT
	(NAME, DESCRIPTION, TYPE_ID, GAME_SYSTEM_ID, NOVA_YEAR, EVENT_START, EVENT_END, IS_UNIQUE, IS_WEEKEND_BADGE_REQ, PRICE, AVAILABLE_QTY, NOTE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, CREATED_BY, CREATED_DATE)
VALUES 
	('WM/H - Tierany Tournament',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE()),
	('WM/H - Specialists Tournament',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE()),
	('WM/H - Trifecta Team Tournament',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE()),
	('WM/H - Death Race',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE()),
	('WM/H - Who''s the Boss',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE()),
	('WM/H - Harcore Tournament',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE()),
	('WM/H - Old-Style Masters',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE()),
	('WM/H - Flanks',NULL,2,5,2013,NULL,NULL,1,1,10,NULL,NULL,USER(),SYSDATE(),USER(),SYSDATE())

;


INSERT INTO CHANGELOG
	(SCRIPT, RUN_DATE)
VALUES
	('010001014_Insert_Warma_Evenets.sql',NOW())
;