
-- Create tables to support user management

-- DDL

CREATE TABLE LT_ACCOUNT_STATUS (
	ID 				INT NOT NULL,
	LABEL			VARCHAR(50) NOT NULL,
	DESCRIPTION		VARCHAR(100) NULL,
	CONSTRAINT PK_ACTSTATUS_ID PRIMARY KEY (ID)
	);

CREATE TABLE LT_USER_ROLE (
	ID				INT NOT NULL,
	LABEL			VARCHAR(50) NOT NULL,
	DESCRIPTION		VARCHAR(255) NOT NULL,
	CONSTRAINT	PK_USER_ROLE_ID PRIMARY KEY (ID)
	);
	
CREATE TABLE USER (
	ID 					INT NOT NULL,
	USERNAME 			VARCHAR(50) NOT NULL,
	FIRST_NAME 			VARCHAR(50) NOT NULL,
	MIDDLE_NAME 		VARCHAR(50) NULL,
	LAST_NAME			VARCHAR(50) NOT NULL,
	EMAIL				VARCHAR(255) NOT NULL,
	ACCOUNT_STATUS		INT NOT NULL,
	CNT_LOGIN_FAIL		INT NOT NULL,
	LAST_LOGIN_DATE		DATETIME NOT NULL,
	IS_PW_CHANGE_REQUIRED	BIT NOT NULL,
	LAST_MODIFIED_BY 	VARCHAR(55) NOT NULL,
	LAST_MODIFIED_DATE 	DATETIME NOT NULL,
	CREATED_BY 			VARCHAR(55) NOT NULL,
	CREATED_DATE 		DATETIME NOT NULL,
	CONSTRAINT PK_USER_ID PRIMARY KEY (ID),
	CONSTRAINT FK_ACTSTATUS_USER_ID FOREIGN KEY (ACCOUNT_STATUS)
		REFERENCES LT_ACCOUNT_STATUS (ID)
	);

CREATE TABLE PASSWORD_HISTORY (
	ID					INT NOT NULL,
	USER_ID				INT NOT NULL,
	CHANGED_DATE		DATETIME NOT NULL,
	PASSWORD_VALUE		VARCHAR(255) NOT NULL,
	LAST_MODIFIED_BY 	VARCHAR(55) NOT NULL,
	LAST_MODIFIED_DATE 	DATETIME NOT NULL,
	CREATED_BY 			VARCHAR(55) NOT NULL,
	CREATED_DATE 		DATETIME NOT NULL,
	CONSTRAINT PK_PASSWORD_HIST_ID PRIMARY KEY (ID),
	CONSTRAINT FK_PWDHIST_ID_USER_ID FOREIGN KEY (USER_ID)
		REFERENCES USER (ID)
	) ;

CREATE TABLE X_USER_USER_ROLE (
	ID					INT NOT NULL,
	USER_ID				INT NOT NULL,
	USER_ROLE			INT NOT NULL,
	LAST_MODIFIED_BY 	VARCHAR(55) NOT NULL,
	LAST_MODIFIED_DATE 	DATETIME NOT NULL,
	CREATED_BY 			VARCHAR(55) NOT NULL,
	CREATED_DATE 		DATETIME NOT NULL,
	CONSTRAINT PK_USR_USRROLE_ID PRIMARY KEY (ID),
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID)
		REFERENCES USER (ID),
	CONSTRAINT FK_USER_ROLE_ID FOREIGN KEY (USER_ROLE)
		REFERENCES LT_USER_ROLE (ID)
	) ;
	
-- DML for initial seed of status

INSERT INTO LT_ACCOUNT_STATUS (ID, LABEL, DESCRIPTION)
VALUES	
	(1,'Active','User is currently active'),
	(2,'Inactive','User is inactive and cannot log in'),
	(3,'Locked','User account is locked'),
	(4,'Pending','User account is pending approval')
	;

INSERT INTO LT_USER_ROLE (ID, LABEL, DESCRIPTION)
VALUES
	(1,'Admin','Application administrator'),
	(2,'User','Basic application user'),
	(3,'Judge','User with judge permissions')
	;

INSERT INTO CHANGELOG
	(SCRIPT, RUN_DATE)
VALUES
	('010002001_create_user_management_tables.sql',NOW())
;
