17a18
>   KEY FK_APP_ENTRY_EVENT_ID (EVENT_ID),
19a21
>   CONSTRAINT FK_APP_ENTRY_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID),
41c43
<   CONSTRAINT FK_APP_SCORE_JUDGE_ID FOREIGN KEY (JUDGE_ID) REFERENCES `user` (ID)
---
>   CONSTRAINT FK_APP_SCORE_JUDGE_ID FOREIGN KEY (JUDGE_ID) REFERENCES `USERS` (ID)
228c230
< CREATE TABLE lt_user_role (
---
> CREATE TABLE LT_USERS_ROLE (
239c241
<   USER_ID int(11) NOT NULL,
---
>   USERS_ID int(11) NOT NULL,
247,248c249,250
<   KEY FK_PWDHIST_ID_USER_ID (USER_ID),
<   CONSTRAINT FK_PWDHIST_ID_USER_ID FOREIGN KEY (USER_ID) REFERENCES `user` (ID)
---
>   KEY FK_PWDHIST_ID_USERS_ID (USERS_ID),
>   CONSTRAINT FK_PWDHIST_ID_USERS_ID FOREIGN KEY (USERS_ID) REFERENCES `USERS` (ID)
344c346
< CREATE TABLE `user` (
---
> CREATE TABLE USERS (
360,361c362,363
<   KEY FK_ACTSTATUS_USER_ID (ACCOUNT_STATUS),
<   CONSTRAINT FK_ACTSTATUS_USER_ID FOREIGN KEY (ACCOUNT_STATUS) REFERENCES lt_account_status (ID)
---
>   KEY FK_ACTSTATUS_USERS_ID (ACCOUNT_STATUS),
>   CONSTRAINT FK_ACTSTATUS_USERS_ID FOREIGN KEY (ACCOUNT_STATUS) REFERENCES LT_ACCOUNT_STATUS (ID)
401c403
< CREATE TABLE x_user_user_role (
---
> CREATE TABLE X_USERS_ROLE (
403,404c405,406
<   USER_ID int(11) NOT NULL,
<   USER_ROLE int(11) NOT NULL,
---
>   USERS_ID int(11) NOT NULL,
>   USERS_ROLE int(11) NOT NULL,
410,413c412,415
<   KEY FK_USER_ID (USER_ID),
<   KEY FK_USER_ROLE_ID (USER_ROLE),
<   CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES `user` (ID),
<   CONSTRAINT FK_USER_ROLE_ID FOREIGN KEY (USER_ROLE) REFERENCES lt_user_role (ID)
---
>   KEY FK_USERS_ID (USERS_ID),
>   KEY FK_USERS_ROLE_ID (USERS_ROLE),
>   CONSTRAINT FK_USERS_ID FOREIGN KEY (USERS_ID) REFERENCES `USERS` (ID),
>   CONSTRAINT FK_USERS_ROLE_ID FOREIGN KEY (USERS_ROLE) REFERENCES LT_USERS_ROLE (ID)
